version: '3.8'
services:
    db:
        image: postgres:13
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret
        ports:
            - '54321:5432'
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local
